name: googletest

on: push

jobs:
  googletest_macos_clang_no_stl:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: get cmake
        uses: lukka/get-cmake@latest

      - name: build and run tests
        run:  mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DUTI_RELEASE=ON -DUTI_HAS_STL=OFF -DUTI_TEST=ON && make -j8 && ./test/gtest_uti

  googletest_macos_clang:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: get cmake
        uses: lukka/get-cmake@latest

      - name: build and run tests
        run:  mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DUTI_RELEASE=ON -DUTI_HAS_STL=ON -DUTI_TEST=ON && make -j8 && ./test/gtest_uti

  googletest_ubuntu_clang_no_stl:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: get cmake
        uses: lukka/get-cmake@latest

      - name: get clang18
        run:  mkdir llvm && cd llvm && wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 18

      - name: build and run tests
        run:  export CXX=$(which clang++18) && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DUTI_RELEASE=ON -DUTI_HAS_STL=OFF -DUTI_TEST=ON && make -j8 && ./tests/gtest_nplib

  googletest_ubuntu_clang:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: get cmake
        uses: lukka/get-cmake@latest

      - name: get clang18
        run:  mkdir llvm && cd llvm && wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 18

      - name: build and run tests
        run:  export CXX=$(which clang++18) && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DUTI_RELEASE=ON -DUTI_HAS_STL=ON -DUTI_TEST=ON && make -j8 && ./tests/gtest_nplib

  googletest_ubuntu_gcc_no_stl:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: get cmake
        uses: lukka/get-cmake@latest

      - name: update g++
        run:  sudo apt install g++-14

      - name: build and run tests
        run:  export CXX=$(which g++-14) && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DUTI_RELEASE=ON -DUTI_HAS_STL=OFF -DUTI_TEST=ON && make -j8 && ./tests/gtest_nplib

  googletest_ubuntu_gcc:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: get cmake
        uses: lukka/get-cmake@latest

      - name: update g++
        run:  sudo apt install g++-14

      - name: build and run tests
        run:  export CXX=$(which g++-14) && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DUTI_RELEASE=ON -DUTI_HAS_STL=ON -DUTI_TEST=ON && make -j8 && ./tests/gtest_nplib
